### ISSUE TITLE
Make reported mysql version flexible

### ISSUE THREAD

**Issue by HansH111** [sjinks/mysql-honeypotd#1]
adapt globals and protocol.c to allow different mysql versions to be reported instead of the fixed 5.7.19

for instance in protocols.c,  some small code changes will allow that...

```
+ if (globals.version && strlen(globals.version)==6) {
+        strcpy(&result[5],globals.version);
+ }

```
Attached full diff for this functionality
[version_diff.txt](https://github.com/sjinks/mysql-honeypotd/files/1484562/version_diff.txt)

**Comment by sjinks** [comment]
Implemented in 0.3.0, thank you!
