### ISSUE TITLE
view password?

### ISSUE THREAD

**Issue by glira** [sjinks/mysql-honeypotd#11]
is possible view password that user try

**Comment by sjinks** [comment]
Unfortunately, only in very rare cases when the client uses a `mysql_clear_password` authentication plugin. By default, the `mysql_native_password` authentication plugin uses a one-way hashing which makes it impossible to retrieve the original password.

**Comment by s0i37** [comment]
Uncomment `/* const uint8_t* pwd_pos; */` and use this variable - it points to 20-bytes hash.
