### ISSUE TITLE
Design Flaw Enhancement

### ISSUE THREAD

**Issue by hackdefendr** [sjinks/mysql-honeypotd#3]
How hard would it be to add functionality to this honeypot similar to what is talked about here:

https://www.bleepingcomputer.com/news/security/mysql-design-flaw-allows-malicious-servers-to-steal-files-from-clients/

Discuss?

**Comment by sjinks** [comment]
I am not sure if it is possible here… As far as I understand, a malicious MySQL **server** asks a client to transfer it a local file. This honeypot aims at catching **clients** brute forcing passwords.

In order to detect a malicious server, you probably need a scanner, not a honeypot.
