### ISSUE TITLE
Enhancement request: Log to a file, not syslog

### ISSUE THREAD

**Issue by josenk** [sjinks/mysql-honeypotd#7]
I prefer to log to a separate file, not using syslog.

  Or simply the ability to just turn off syslog, it's not needed if you wanted to run this in a docker container.

**Comment by sjinks** [comment]
Cannot promise I will do this fast — have a lot of work at the moment :-( but if everything is OK, will try to look into this on the weekend

**Comment by sjinks** [comment]
if I add an option to log to stderr instead of syslog, is that a good option? In theory, you can then redirect stderr to the file you want.

**Comment by josenk** [comment]
Correct, logging to stdout only is perfect.
   Perhaps, when using the -f (forground) option, all logs go to stdout.  I didn't look at all the code, but I think it does that already???   Just need to add an option to stop sending to syslog.

No rush for this.   Just an ER.

**Comment by sjinks** [comment]
Done, please take a look. Sorry that it took so long.

**Comment by sjinks** [comment]
Just in case: I have created a Docker image for mysql-honeypotd: https://hub.docker.com/r/wildwildangel/mysql-honeypotd

**Comment by josenk** [comment]
This is awesome!   Thanks.
